@api = http://localhost:4001
GET {{ api }}/api/products/

###

POST {{ api }}/api/products/
Content-Type: application/json

{
    "name"          : "CM_PUNK Mejor en el mundo lucha libre camiseta",
    "description"   : "CM Punk Best In The World Wrestling T Shirt está preencogida y prelavada. Utilizamos camisetas 100% algodón. Ofrecemos una serie de diferentes estilos y colores! ¡Pídanos más detalles! Todas nuestras camisas están hechas a medida para ti, y fabricadas en Norteamérica. Asegúrate de que este producto viene de THREADSQUAD, todas las demás camisas son imitaciones.",
    "category"      : "t-shirt",
    "brand"         : "wwe",
    "price"         : 17.99,
    "image"         : "cm_punk.jpg",
    "stock"         : 15
}