@api = http://localhost:4001
POST {{ api }}/api/users/signup
Content-Type: application/json

{
    "name"        : "Joseph",
    "lastname"    : "Joestar",
    "phone"       : 123456777,
    "image"       : "https://i.pinimg.com/474x/5d/8b/aa/5d8baaaa56d61e11e45d43e8e2744efc.jpg",
    "mail"        : "Joseph@gmail.com",
    "password"    : "456"
}

###

POST {{ api }}/api/users/signin
Content-Type: application/json

{
    "mail"        : "jairo@gmail.com",
    "password"    : "123456"
}

###

